language: objective-c
xcode_workspace: Gallery.xcworkspace
xcode_scheme: Gallery
before_install:
  - rvm use ruby-2.0.0-p247
  - ls /Users/travis/.rvm/gems/ruby-2.0.0-p247/bin
  - gem install cocoapods
  - ls /Users/travis/.rvm/gems/ruby-2.0.0-p247/bin
  - which pod
