language: objective-c
xcode_workspace: Gallery.xcworkspace
xcode_scheme: Gallery
before_install:
# - rvm use 2.0
# - ls /Users/travis/.rvm/gems/ruby-2.0.0-p247/bin
- gem install --no-rdoc --no-ri cocoapods
# - ls /Users/travis/.rvm/gems/ruby-2.0.0-p247/bin
- which pod
before_script:
- export LANG=en_US.UTF-8
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in travis_scripts/profiles/adhoc.mobileprovision.enc -d -a -out travis_scripts/profiles/adhoc.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in travis_scripts/certs/dist.cer.enc -d -a -out travis_scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in travis_scripts/certs/dist.p12.enc -d -a -out travis_scripts/certs/dist.p12
- ./travis_scripts/add-key.sh
- security find-identity
- security find-certificate
script:
- xctool -workspace Gallery.xcworkspace -scheme Gallery -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
after_success:
- ./travis_scripts/sign-and-upload.sh
after_script:
- ./travis_scripts/remove-key.sh
env:
  global:
  - APP_NAME="Gallery"
  - 'DEVELOPER_NAME="iPhone Distribution: XUYANG WANG (G6B63JMW7X)"'
  - PROFILE_NAME="adhoc"
  - secure: F5ihzhQLoDJ0rQ5CoRTBR1n4uzRcY5KY5VSH9rBipYklzN8Qux16OFLXljie/0OTMK/uezSexB2cknXEHu2fvBTm7CPrEAas/UeNKiBfKKBjStK2GDOsv+csgiUnKvM615ZLUZAFZMFH592CxDo4gQkcUG4vxV8iXw7nS5XUikQ=
  - secure: Zn8JU6ITxAzMO3wueDY0WWVGcYZW2vB3dWC70GTHhy1bpvR5qLpmz9jEjGhzyFdzoUYtYE4ZdwSaThJvNtdtPj64ead/6WysXpH3aQ/SnN9N557MD5V9eGNYTy5YJodLFA78jq4b0+BPGvUQ3znt4TTzA9m1VQs4cBd6LpcPMc0=
  - secure: sijkuU+6e9/WJX6M/yyT7+jE01qHRN8MkwCmQfyn/Qn/oqbZCImwVWV9oXhlU84g/EvyhBkXpMpQXyFdwjB18vWybGK5tOqifeEe/Djlh6WkJCW4+BACSgfvKBO8EHMVm4MgwPLHlO7nYmEcX8bHXsKikPzz1eY+ly7TWQQ5e1M=
  - secure: BeYnXDoKLcEN45CJl6tPPkOoqS6IIJDXmlaStDkXSbhrVz4usiK38xQ7oiUe8Rwi5LP2Kd01ol+2+JldJt+1xfLMD6EtYX7TJLfyzrV0/K4TIfwdB4jLnTbWmSal+CvesMttuF307cbUMfd8U6JLFlrbYgT4JcPyDyXvSk8MAW4=
